config/routes.rb
RedditClone::Application.routes.draw do
  root 'subs#index'

  resources :users
  resources :subs
  resource :session
  resources :comments, only: [:destroy]

  resources :links do
    resources :comments, only: [:create] do
      resources :comments, only: [:create]
    end

    member do
      post 'upvote'
      post 'downvote'
    end
  end
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id           :integer          not null, primary key
#  title        :string(255)      not null
#  url          :string(255)      not null
#  text         :text
#  created_at   :datetime
#  updated_at   :datetime
#  submitter_id :integer
#

class Link < ActiveRecord::Base
  validates :title, :url, :parent_subs, presence: true

  has_many :link_subs
  has_many :parent_subs, through: :link_subs, source: :sub
  belongs_to :submitter, class_name: 'User'
  has_many :comments
  has_many :user_votes

  def comments_by_parent_id
    parent_hash = Hash.new { |h, k| h[k] = [] }
    comments.each do |comment|
      parent_hash[comment.parent_comment_id] << comment
    end

    parent_hash
  end

  def vote_count
    votes = user_votes
    votes.inject(0) do |accum, vote|
      vote.upvote ? accum + 1 : accum -1
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  include LinksHelper

  before_action :require_login, except: [:index, :show]
  before_action :require_submitter, only: [:edit, :update]

  def new
    @link = Link.new
    @subs = Sub.all
  end

  def create
    @link = current_user.submitted_links.new(link_params)

    if @link.save
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :new
    end
  end

  def show
    @link = Link.find(params[:id])
    @comment = current_user.authored_comments.new
    @comment.link_id = @link.id

    @comments = @link.comments_by_parent_id
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])

    if @link.update_attributes(link_params)
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :edit
    end
  end

  def upvote
    create_vote(true)
  end

  def downvote
    create_vote(false)
  end
end

app/helpers/links_helper.rb
module LinksHelper
  def require_submitter
    @link = Link.find(params[:id])
    redirect_to link_url(@link) unless @link.submitter_id = current_user.id
  end

  def link_params
    params.require(:link).permit(:title, :url, :text, parent_sub_ids: [])
  end

  def create_vote(bool)
    @vote = UserVote.new(
      user_id: current_user.id,
      link_id: params[:id],
      upvote: bool
    )

    flash[:errors] = ["Sorry, I didn't register that vote"] unless @vote.save
    redirect_to link_url(@vote.link)
  end
end

app/views/links/_comment.html.erb
<h4>By <%= comment.author.username %></h4>
<p><%= comment.body %></p>

<%= render 'comments/form', parent_comment: comment, nested: true %>

<ul>
<% comment_hash[comment.id].each do |child_comment| %>
  <li>
    <%= render 'comment', comment: child_comment, comment_hash: comment_hash %>
  </li>
<% end %>
</ul>

app/views/links/new.html.erb
<h1>Add new link</h1>

<form action="<%= links_url %>" method="post">
  <%= form_auth_token %>

    <label>Title
      <input type="text" name="link[title]" value="<%= @link.title %>">
    </label><br>

    <label>URL
      <input type="text" name="link[url]" value="<%= @link.url %>">
    </label><br>

    <label>Text
      <textarea name="link[text]"><%= @link.text %></textarea>
    </label><br><br>

    <h3>Subs</h3>
    <% @subs.each do |sub| %>
      <label>
        <input type="checkbox" name="link[parent_sub_ids][]" value="<%= sub.id %>">
        <%= sub.name %>
      </label>
      <br>
    <% end %>
    <br>
  <input type="submit" value="Add New Link">

</form>

app/views/links/show.html.erb
<h1><%= @link.title %></h1>
<h5>Vote count: <%= @link.vote_count %></h5>

<% unless @link.user_votes.map(&:user_id).include?(current_user.id)%>
<%= button_to 'Upvote', upvote_link_url(@link) %>
<%= button_to 'Downvote', downvote_link_url(@link) %>
<% end %>
<%= image_tag @link.url %><br>

<% if current_user.id == @link.id %>
  <%= link_to 'Edit Link', edit_link_url(@link) %>
<% end %>

<h3>Comments</h3>

<ul>
<% @comments[nil].each do |comment| %>
  <li><%= render 'comment', comment: comment, comment_hash: @comments %></li>
<% end %>
</ul>


<h4>Add a comment</h4>
  <%= render 'comments/form', comment: @comment, nested: false %>