config/routes.rb
RedditClone::Application.routes.draw do
  root 'subs#index'

  resources :users
  resources :subs
  resource :session
  resources :comments, only: [:destroy]

  resources :links do
    resources :comments, only: [:create] do
      resources :comments, only: [:create]
    end

    member do
      post 'upvote'
      post 'downvote'
    end
  end
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  name         :string(255)      not null
#  moderator_id :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Sub < ActiveRecord::Base
  validates :name, uniqueness: { case_sensitive: false }
  validates :name, :moderator, presence: true

  belongs_to :moderator, class_name: "User"
  has_many :link_subs
  has_many :links, through: :link_subs, source: :link, inverse_of: :parent_subs
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  include SubsHelper

  before_action :require_login, except: [:index, :show]
  before_action :require_moderator, only: [:edit, :update]

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
    @links = @sub.links.sort_by(&:vote_count).reverse
  end

  def new
    @sub = Sub.new
    5.times { @sub.links.build }
  end

  def create
    @sub = current_user.moderated_subs.new(sub_params)
    @sub.links.new(link_params)

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      (5 - @sub.links.length).times { @sub.links.build }

      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end
end

app/helpers/subs_helper.rb
module SubsHelper
  def require_moderator
    sub = Sub.find(params[:id])
    redirect_to subs_url unless sub.moderator_id == current_user.id
  end

  def sub_params
    params.require(:sub).permit(:name)
  end

  def link_params
    params.permit(link: [:title, :url, :text] )
          .require(:link)
          .values
          .reject{ |link| link.values.all?(&:blank?) }
          .map { |link| link.submitter_id = current_user.id }
  end
end

app/views/subs/edit.html.erb
<h1>Edit sub</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <%= form_auth_token %>
  <input type="hidden" name="_method" value="patch">

  <label>Name
    <input type="text" name="sub[name]" value="<%= @sub.name %>">
  </label><br><br>

  <input type="submit" value="Update Sub">
</form>

app/views/subs/index.html.erb
<h1>All subs</h1>

<p><%= link_to "Add new sub", new_sub_url %></p>

<% @subs.each do |sub| %>
<p><%= link_to sub.name, sub_url(sub) %></p>
<% end %>

app/views/subs/new.html.erb
<h1>Create new sub</h1>

<form action="<%= subs_url %>" method="post">
  <%= form_auth_token %>
  <label>Name
    <input type="text" name="sub[name]" value="<%= @sub.name %>">
  </label><br><br>

  <% @sub.links.each_with_index do |link, i| %>
    <label>Title
      <input type="text" name="link[<%= i %>][title]" value="<%= link.title %>">
    </label><br>

    <label>URL
      <input type="text" name="link[<%= i %>][url]" value="<%= link.url %>">
    </label><br>

    <label>Text
      <textarea name="link[<%= i %>][text]"><%= link.text %></textarea>
    </label><br><br>
  <% end %>

  <input type="submit" value="Create New Sub">

</form>

app/views/subs/show.html.erb
<% if current_user.id == @sub.moderator_id %>
  <%= link_to 'Edit Sub', edit_sub_url(@sub) %>
<% end %>

<h1><%= @sub.name %></h1>
<h3>Moderator: <%= @sub.moderator.username %></h3>

<% @links.each do |link| %>
<p><%= link.vote_count%> <%= link_to link.title, link_url(link) %></p>
<% end %>